SELECT DEPARTMENT_NAME
  FROM DEPARTMENTS D INNER JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 WHERE E.SALARY = (SELECT MAX(F.SALARY) 
                     FROM EMPLOYEES F);
                        